--- #YAML:1.0
name:                Catalyst-Plugin-Session-State-Cookie
version:             0.07
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Catalyst::Plugin::Session:     0.06
    Class::Accessor::Fast:         0
    Test::MockObject:              1.01
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
