---
name: Catalyst-Plugin-Session-State-Cookie
version: 0.02
author: ~
abstract: Maintain session IDs using cookies.
license: perl
requires:
  Catalyst::Plugin::Session: 0.01
  Test::MockObject: 1.01
provides:
  Catalyst::Plugin::Session::State::Cookie:
    file: lib/Catalyst/Plugin/Session/State/Cookie.pm
    version: 0.02
generated_by: Module::Build version 0.2611
