---
abstract: 'Maintain session IDs using cookies.'
author:
  - 'Yuval Kogman <nothingmuch@woobling.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Moose: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.910'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-Session-State-Cookie
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.80005
  Catalyst::Plugin::Session: 0.19
  MRO::Compat: 0
  Moose: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://dev.catalyst.perl.org/repos/Catalyst/trunk/Catalyst-Plugin-Session-State-Cookie/
version: 0.15
