# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-Session-State-Cookie
version:      0.06
version_from: lib/Catalyst/Plugin/Session/State/Cookie.pm
installdirs:  site
requires:
    Catalyst::Plugin::Session:     0.06
    Test::MockObject:              1.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
